# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: required

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libproj-dev libgdal-dev

r_github_packages:
- hadley/devtools
